title: HHMI Social Media Calendar 
email: diaze@janelia.hhmi.org
description: > # this means to ignore newlines until "baseurl:"
  Social media calendar for the HHMI Communications department.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: social 
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
